### ISSUE TITLE
Assertion Error 

### ISSUE THREAD

**Issue by IamVNIE** [morlandi/django-datatables-view#11]
I am unable to use the library. Followed the starting tutorial in readme but cant get it to work. 
I'm using Python 3.5.2 and Django 2.2.10.
Can you point to a working project using this library?

```
C:\Python35\lib\site-packages\datatables_view\views.py in dispatch
            elif action == 'details':
                return JsonResponse({
                    'html': self.render_row_details(request.REQUEST.get('id'), request),
                })
            response = super(DatatablesView, self).dispatch(request, *args, **kwargs)
        else:
            assert False …
            #response = HttpResponse(self.render_table(request))
        return response
    # def render_row_details(self, id, request=None):
    #     obj = self.model.objects.get(id=id)
    #     fields = [f.name for f in self.model._meta.get_fields() if f.concrete]
```

**Comment by morlandi** [comment]
@IamVNIE I plan to add a demo project soon, as time allows.
In the meantime, you might want to start with the example given here:

https://github.com/morlandi/django-datatables-view#13basic-datatablesview

**Comment by keniobats** [comment]
I'm having the same issue with Python 3.7.4 and Django 3.0.7.

Any hints about this? Thanks a lot!

urls.py:
`from whistleblower import datatables_views`

`path('denuncia/report_search/', datatables_views.RegisterDatatablesView.as_view(), name="datatable_registers"),`


datatables_views.py:

`from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator

from datatables_view.views import DatatablesView

from .models import Report


@method_decorator(login_required, name='dispatch')
class RegisterDatatablesView(DatatablesView):

    model = Report
    title = 'Hechos'

    column_defs = [
    	{
            'name': 'id',
            'visible': False,
        },
        {
            'name': 'user',
        }, {
            'name': 'incident_datetime',
        },{
            'name': 'casefile',
        }, {
            'name': 'address',
        }, {
            'name': 'locality',
        }, {
            'name': 'report_type',
        }, {
            'name': 'procedure_type',
        }, {
            'name': 'district',
        },
        {
            'name': 'jurisdiction',
        },
        {
            'name': 'incident_description',
        }
    ]`





> Request Method: GET
> http://localhost:8000/denuncia/report_search/
> 3.0.7
> AssertionError
> /Users/keniobats/.pyenv/versions/bigeye/lib/python3.7/site-packages/datatables_view/views.py in dispatch, line 381
> /Users/keniobats/.pyenv/versions/bigeye/bin/python
> 3.7.4
> ['/Users/keniobats/Dev/bigeye',  '/Users/keniobats/.pyenv/versions/3.7.4/lib/python37.zip',  '/Users/keniobats/.pyenv/versions/3.7.4/lib/python3.7',  '/Users/keniobats/.pyenv/versions/3.7.4/lib/python3.7/lib-dynload',  '/Users/keniobats/.pyenv/versions/bigeye/lib/python3.7/site-packages',  '/Users/keniobats/.pyenv/versions/bigeye/lib/python3.7/site-packages/odf',  '/Users/keniobats/.pyenv/versions/bigeye/lib/python3.7/site-packages/odf',  '/Users/keniobats/.pyenv/versions/bigeye/lib/python3.7/site-packages/odf',  '/Users/keniobats/.pyenv/versions/bigeye/lib/python3.7/site-packages/odf',  '/Users/keniobats/.pyenv/versions/bigeye/lib/python3.7/site-packages/odf',  '/Users/keniobats/.pyenv/versions/bigeye/lib/python3.7/site-packages/odf',  '/Users/keniobats/.pyenv/versions/bigeye/lib/python3.7/site-packages/odf']

**Comment by morlandi** [comment]
@IamVNIE and @keniobats ... please see my comments here:

https://github.com/morlandi/django-ajax-datatable/issues/1
